---
include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right

# Renames the build artifact to "Firmware #<run number>"
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main

  rename-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: firmware
          path: ./firmware
      - name: Rename with build number
        run: mv ./firmware ./firmware-renamed
      - uses: actions/upload-artifact@v4
        with:
          name: "Firmware #${{ github.run_number }}"
          path: ./firmware-renamed
