name: Build ZMK firmware
on: [workflow_dispatch]

permissions:
  actions: write

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

  # Renames the build artifact to "Firmware #<run number>"
  rename-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: firmware
          path: ./firmware
      - name: Rename with build number
        run: mv ./firmware ./firmware-renamed
      - uses: actions/upload-artifact@v4
        with:
          name: "Firmware #${{ github.run_number }}"
          path: ./firmware-renamed

      - name: Delete original artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ARTIFACT_ID=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            --jq '.artifacts[] | select(.name=="firmware") | .id')
          gh api -X DELETE repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/$ARTIFACT_ID
